[2021-09-05 13:08:34,143] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: airflow-db-cleanup.cleanup_DagModel 2021-09-04T00:00:00+00:00 [queued]>
[2021-09-05 13:08:34,191] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: airflow-db-cleanup.cleanup_DagModel 2021-09-04T00:00:00+00:00 [queued]>
[2021-09-05 13:08:34,191] {taskinstance.py:1094} INFO - 
--------------------------------------------------------------------------------
[2021-09-05 13:08:34,191] {taskinstance.py:1095} INFO - Starting attempt 1 of 2
[2021-09-05 13:08:34,191] {taskinstance.py:1096} INFO - 
--------------------------------------------------------------------------------
[2021-09-05 13:08:34,227] {taskinstance.py:1114} INFO - Executing <Task(PythonOperator): cleanup_DagModel> on 2021-09-04T00:00:00+00:00
[2021-09-05 13:08:34,230] {standard_task_runner.py:52} INFO - Started process 4014 to run task
[2021-09-05 13:08:34,246] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'airflow-db-cleanup', 'cleanup_DagModel', '2021-09-04T00:00:00+00:00', '--job-id', '221', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/airflow-db-cleanup.py', '--cfg-path', '/tmp/tmppcrod423', '--error-file', '/tmp/tmp24gz65t6']
[2021-09-05 13:08:34,247] {standard_task_runner.py:77} INFO - Job 221: Subtask cleanup_DagModel
[2021-09-05 13:08:34,372] {logging_mixin.py:109} INFO - Running <TaskInstance: airflow-db-cleanup.cleanup_DagModel 2021-09-04T00:00:00+00:00 [running]> on host 2bce3265bb98
[2021-09-05 13:08:34,484] {taskinstance.py:1251} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=operations
AIRFLOW_CTX_DAG_ID=airflow-db-cleanup
AIRFLOW_CTX_TASK_ID=cleanup_DagModel
AIRFLOW_CTX_EXECUTION_DATE=2021-09-04T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-09-04T00:00:00+00:00
[2021-09-05 13:08:34,485] {airflow-db-cleanup.py:265} INFO - Retrieving max_execution_date from XCom
[2021-09-05 13:08:34,511] {taskinstance.py:1462} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/taskinstance.py", line 1164, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/taskinstance.py", line 1282, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/usr/local/lib/python3.8/dist-packages/airflow/models/taskinstance.py", line 1312, in _execute_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.8/dist-packages/airflow/operators/python.py", line 150, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.8/dist-packages/airflow/operators/python.py", line 161, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/usr/local/airflow/dags/airflow-db-cleanup.py", line 269, in cleanup_function
    max_date = dateutil.parser.parse(max_date)  # stored as iso8601 str in xcom
  File "/usr/local/lib/python3.8/dist-packages/dateutil/parser/_parser.py", line 1368, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/dateutil/parser/_parser.py", line 640, in parse
    res, skipped_tokens = self._parse(timestr, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/dateutil/parser/_parser.py", line 719, in _parse
    l = _timelex.split(timestr)         # Splits the timestr into tokens
  File "/usr/local/lib/python3.8/dist-packages/dateutil/parser/_parser.py", line 201, in split
    return list(cls(s))
  File "/usr/local/lib/python3.8/dist-packages/dateutil/parser/_parser.py", line 69, in __init__
    raise TypeError('Parser must be a string or character stream, not '
TypeError: Parser must be a string or character stream, not NoneType
[2021-09-05 13:08:34,519] {taskinstance.py:1505} INFO - Marking task as UP_FOR_RETRY. dag_id=airflow-db-cleanup, task_id=cleanup_DagModel, execution_date=20210904T000000, start_date=20210905T130834, end_date=20210905T130834
[2021-09-05 13:08:34,573] {local_task_job.py:151} INFO - Task exited with return code 1
[2021-09-05 13:08:34,630] {local_task_job.py:261} INFO - 0 downstream tasks scheduled from follow-on schedule check
